version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '8000:8000'
    environment:
      - BOT_TOKEN=7462802231:AAGyMiw7WwCjXxOnnycrm2EkhVBU_VpUpOo
      - CHAT_ID=924278580
